### ISSUE TITLE
how to remove interpolation while moving ur5 with moveit?

### ISSUE THREAD

**Issue by enrico-g** [ThomasTimm/ur_modern_driver#180] opened 2018-07-05 11:02 UTC
Hi all,

I am trying to make my UR5 avoid simple fixed obstacles by moving it with Moveit, using the OMPL library.
When i run "ur5_ros_control.launch" everything goes fine until i push "plan" & "execute".
The main problem is that the end-effector reaches the desired position but fails in executing the planned trajectory, because it tends to smooth it causing collisions with the obstacles.
The question is the same as the title: how can I remove the interpolation function making my robot follow the actual trajectory (even if non-optimal)?

I'm using ur_modern_driver (zagitta fork) on ros kinetic, ubuntu 16.04.
The list of commands to connect to real robot and open Rviz:

> roslaunch ur_modern_driver ur5_ros_control.launch limited:=true robot_ip:=192.168.0.9
> 
> roslaunch ur5_moveit_config ur5_moveit_planning_execution.launch limited:=true
> 
> roslaunch ur5_moveit_config 2_moveit_rviz.launch db:=true config:=true

If necessary, I will paste here the code of "ur5_ros_control.launch" file.
Thanks in advance.

**Comment by gavanderhoorn** [comment] 2018-09-03 11:35
This is a duplicate of https://github.com/Zagitta/ur_modern_driver/issues/25.

I've already replied there.

If something is not clear or you require additional information, please comment on https://github.com/Zagitta/ur_modern_driver/issues/25.

**Closed by gavanderhoorn** 2018-09-03 11:35 UTC
